# symlink to ~/.alacritty.yml
# ctrl+shift+f/b - search front/back
font:
  size: 13
window:
  padding:
    x: 20
    y: 20
  dynamic_padding: true
  opacity: 0.84
  decorations: none  # for Wayland dark titlebar lack

schemes:
  ayudark: &ayudark # Default colors
    primary:
      background: "0x0A0E14"
      foreground: "0xB3B1AD"
    # Normal colors
    normal:
      black: "0x01060E"
      red: "0xEA6C73"
      green: "0x91B362"
      yellow: "0xF9AF4F"
      blue: "0x53BDFA"
      magenta: "0xFAE994"
      cyan: "0x90E1C6"
      white: "0xC7C7C7"

    # Bright colors
    bright:
      black: "0x686868"
      red: "0xF07178"
      green: "0xC2D94C"
      yellow: "0xFFB454"
      blue: "0x59C2FF"
      magenta: "0xFFEE99"
      cyan: "0x95E6CB"
      white: "0xFFFFFF"
colors: *ayudark

shell:
  program: /usr/bin/zsh

key_bindings:
  - { key: T, mods: Control|Shift, action: SpawnNewInstance }
